import Head from 'next/head';
import { ReactElement } from 'react';
import DashboardLayout from '../../components/layout/dashboard';
import { NextPageWithLayout } from '../_app';

const Dashboard: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h2 className='text-2xl font-bold text-gray-900 mb-4'>Dashboard</h2>
        <h3 className='text-lg font-medium'>Goals</h3>
        <div>
          <ul role='list' className='marker:text-purple-500 list-disc'>
            <li>
              Add Workspace/Notion module (Todos - Kanban) [Prepare name for the
              module]
            </li>
            <li>Profile form</li>
            <li>Add Projects module</li>
          </ul>
        </div>
      </div>
    </>
  );
};

Dashboard.getLayout = function getLayout(page: ReactElement) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export default Dashboard;
