import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { signIn } from 'next-auth/react';
import { DefaultValues, SubmitHandler, useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import clsx from 'clsx';
import messages from '../constants/messages/auth';
import Card from '../components/module/Card';

const SigninSchema = z.object({
  email: z.string().email({ message: 'Email is invalid' }),
  password: z.string(),
});

type SigninSchemaType = z.infer<typeof SigninSchema>;

const defaultValues: DefaultValues<SigninSchemaType> = {
  email: '',
  password: '',
};

const SigninPage: NextPage = () => {
  const router = useRouter();
  const [error, setError] = React.useState<null | string>(null);
  const methods = useForm<SigninSchemaType>({
    resolver: zodResolver(SigninSchema),
    defaultValues,
  });

  const { handleSubmit, register, formState } = methods;
  const { errors, isSubmitting } = formState;

  const onSubmit: SubmitHandler<SigninSchemaType> = async (data) => {
    setError(null);

    const signInResult = await signIn('credentials', {
      redirect: false,
      email: data.email,
      password: data.password,
    });

    if (!signInResult?.ok && signInResult?.status === 401) {
      setError(messages.signinUnauthorized);
    }

    if (signInResult?.ok) {
      const { query } = router;

      if (query?.from) {
        router.push(query.from as string);
      }
      router.push('/dashboard');
    }
  };

  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main
        id='content'
        role='main'
        className='container max-w-md min-h-screen flex flex-col items-center justify-center mx-auto p-6'
      >
        <Card>
          <div className='text-center'>
            <h1 className='block text-2xl font-bold text-gray-800'>Sign In</h1>
            <p className='mt-2 text-sm text-gray-600'>
              State you're name child
            </p>

            {error ? (
              <p className='text-red-600 text font-semibold'>{error}</p>
            ) : null}
          </div>

          <div className='mt-5'>
            <form onSubmit={handleSubmit(onSubmit)}>
              <div className='grid gap-y-4'>
                <div>
                  <label
                    htmlFor='email'
                    className="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm mb-2"
                  >
                    Email address
                  </label>
                  <div className='relative'>
                    <input
                      type='email'
                      id='email'
                      {...register('email')}
                      className={clsx(
                        errors?.email
                          ? 'border-red-500 text-red-600 focus:border-red-500 focus:ring-red-500'
                          : 'border-gray-200 focus:border-blue-500 focus:ring-blue-500',
                        'py-3 px-4 block w-full rounded-md text-sm disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none'
                      )}
                      disabled={isSubmitting}
                      aria-describedby='email-error'
                    />
                    <div
                      className={clsx(
                        errors?.email ? 'flex items-start' : 'hidden',
                        'absolute inset-y-0 right-0 flex items-center pointer-events-none pr-3'
                      )}
                    >
                      <svg
                        className='h-5 w-5 text-red-500'
                        width='16'
                        height='16'
                        fill='currentColor'
                        viewBox='0 0 16 16'
                        aria-hidden='true'
                      >
                        <path d='M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z' />
                      </svg>
                    </div>
                  </div>
                  <p
                    className={clsx(
                      errors?.email ? '' : 'hidden',
                      'text-xs text-red-600 mt-2'
                    )}
                    id='email-error'
                  >
                    {errors?.email?.message}
                  </p>
                </div>
                <div>
                  <label
                    htmlFor='password'
                    className="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm mb-2"
                  >
                    Password
                  </label>
                  <div className='relative'>
                    <input
                      type='password'
                      id='password'
                      {...register('password')}
                      className={clsx(
                        errors?.password
                          ? 'border-red-500 text-red-600 focus:border-red-500 focus:ring-red-500'
                          : 'border-gray-200 focus:border-blue-500 focus:ring-blue-500',
                        'py-3 px-4 block w-full rounded-md text-sm disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none'
                      )}
                      aria-describedby='password-error'
                      disabled={isSubmitting}
                    />
                    <div
                      className={clsx(
                        errors?.password ? 'flex items-start' : 'hidden',
                        'absolute inset-y-0 right-0 flex items-center pointer-events-none pr-3'
                      )}
                    >
                      <svg
                        className='h-5 w-5 text-red-500'
                        width='16'
                        height='16'
                        fill='currentColor'
                        viewBox='0 0 16 16'
                        aria-hidden='true'
                      >
                        <path d='M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z' />
                      </svg>
                    </div>
                  </div>
                  <p
                    className={clsx(
                      errors?.password ? '' : 'hidden',
                      'text-xs text-red-600 mt-2'
                    )}
                    id='password-error'
                  >
                    {errors?.password?.message}
                  </p>
                </div>
                <button
                  type='submit'
                  className={clsx(
                    isSubmitting ? 'cursor-not-allowed hover:bg-blue-400' : '',
                    'py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm'
                  )}
                  disabled={isSubmitting}
                >
                  {isSubmitting ? (
                    <svg
                      className='w-5 h-5 mr-3 -ml-1 text-white animate-spin'
                      xmlns='http://www.w3.org/2000/svg'
                      fill='none'
                      viewBox='0 0 24 24'
                    >
                      <circle
                        className='opacity-25'
                        cx='12'
                        cy='12'
                        r='10'
                        stroke='currentColor'
                        strokeWidth='4'
                      ></circle>
                      <path
                        className='opacity-75'
                        fill='currentColor'
                        d='M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z'
                      ></path>
                    </svg>
                  ) : null}
                  {isSubmitting ? 'Signing in ...' : 'Sign In'}
                </button>
              </div>
            </form>
          </div>
        </Card>
      </main>
    </>
  );
};

export default SigninPage;
